//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КурсоваяWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderrProduct
    {
        public int id { get; set; }
        public string barcodeProduct { get; set; }
        public int idStaff { get; set; }
        public int idSuppliers { get; set; }
        public int count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
